spring.application.name=app-eve-ms-events
# Cargar credenciales (no versionado)
spring.config.import=classpath:config/private.properties

# DataSource
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

# Swagger
springdoc.api-docs.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Puerto interno específico de este microservicio
server.port=8081
# Dirección del servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Registrar usando IP en lugar del hostname
eureka.instance.prefer-ip-address=true